### ISSUE TITLE
BlockAdapter修正

### ISSUE THREAD

**Issue by mmtsk** [ttk1/PeacefulWorld#29]
現状だとBlockAdapterをAPI側から作成する方法がないため、同方法を追加する

**Comment by mmtsk** [comment]
この方法、何か案があればご教授いただければ。
ちなみにAdapter化した理由は、記録する対象がBlockとは限らずEntityである場合もあるから、で合っています？

**Comment by ttk1** [comment]
SpigotのBlockインターフェースを全て実装する必要はないと考えているからです。

**Comment by mmtsk** [comment]
なるほど、了解です。確認どもでした。

**Comment by ttk1** [comment]
BlockAdapterは使用者が勝手に作成しても影響が出るものではないので、コンストラクタをpublicにするぐらいの対応でいいのではないかと思ってました。

**Comment by ttk1** [comment]
BlockAdapterImplのインスタンスを生成するメソッドを、BlockAdapterインターフェースにstaticメソッドとして作成するのはどうでしょうか。
Streamのofメソッドや、ByteBufferのallocateメソッドなどがこんな感じの実装だと思います。
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/stream/Stream.java#Stream.of%28java.lang.Object%29
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/nio/ByteBuffer.java#ByteBuffer.allocate%28int%29
